version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - db-data:/app
    environment:
      - FLASK_ENV=development

volumes:
  db-data:
